### ISSUE TITLE
ReferenceError: onChange is not defined

### ISSUE THREAD

**Issue by marciomrb** [nutboltu/react-search-field#36]
How I can fix this? thanks

**Comment by nutboltu** [comment]
@marciomrb can you please attach some code snippet or the error log to get more context?

**Comment by marciomrb** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/48094387/104303844-5c51c100-54a9-11eb-9154-08d50b81e70e.png)

**Comment by marciomrb** [comment]
sorry if this is simple, i'm new in react, just learning

**Comment by nutboltu** [comment]
@marciomrb the error is not related to this package. The error explained that `onChange` is not defined. you have to define 
a onChange function and pass it to the component.
```
function MyComponent () {
   // Note: here you are defining the function onChange.
    function onChange() {
    }
    return (
       <SearchField
        placeholder="Search..."
        onChange={onChange}
        searchText="This is initial search text"
        classNames="test-class"
      />
    );
}
```

Also I would suggest to use [stackoverflow](https://stackoverflow.com/) for any question instead of issues. Hope that helps you! 👋
